### ISSUE TITLE
Build log is showing absolute path

### ISSUE THREAD

**Issue by bernhard-eiling** [veeso/ios-media-player#4]
When building, the log is showing information about the absolute path of the filesystem of one of the developers.
Could you please remove this information?

![bildschirmfoto 2015-10-29 um 13 39 47](https://cloud.githubusercontent.com/assets/1726410/10818541/96f66f88-7e42-11e5-86f8-a51c7649db94.png)

**Comment by ov1d1u** [comment]
Fixed :)
